# Autogenerated at 2026-06-09T19:00:31.850551
# Run _flutter_version_update.dart to update.

FLUTTER_URL='https://storage.googleapis.com/flutter_infra_release/releases/'
FLUTTER_WINDOWS_VERSION='3.44.1'
FLUTTER_WINDOWS_ARCHIVE='stable/windows/flutter_windows_3.44.1-stable.zip'
FLUTTER_WINDOWS_SHA256='1e83bc8c032ea7f11a41a8f5e2853f7793ebcddacb5268cb0d3409023932091e'
FLUTTER_LINUX_VERSION='3.44.1'
FLUTTER_LINUX_ARCHIVE='stable/linux/flutter_linux_3.44.1-stable.tar.xz'
FLUTTER_LINUX_SHA256='287937458126a53284ed112c8c7dbc647bea2d09ab65d46e2d5cf94e901aac69'
FLUTTER_MACOS_VERSION='3.44.1'
FLUTTER_MACOS_ARCHIVE='stable/macos/flutter_macos_3.44.1-stable.zip'
FLUTTER_MACOS_SHA256='d62c7e9ca7c73e37c52db8fc982f77fa32d4da29bfe60779f5812e5cdcb54946'
